language: python
python:
  - 3.6

before_install:
  - python -m pip install -U pip

install:
  - python -m pip install -r requirements.txt
  - pip install coveralls
  - pip install .

script:
  - coverage run api_888_interview/test/test_event.py

after_success:
  - coveralls
