language: python
python:
  - 3.6

before_install:
  - python -m pip install -U pip

install:
  - python -m pip install -r requirements.txt

script:
  - python -m unittest

after_success:
  - coveralls
