language: python
python:
  - 3.6

before_install:
  - python -m pip install -U pip

install:
  - python -m pip install -r requirements.txt
  - pip install codecov coveralls
  - pip install .

script:
  - coverage run --append ./api_888_interview/test/test_event.py
