language: python
python:
  - 3.6

before_install:
  - python -m pip install -U pip

install:
  - python -m pip install -r api_888_interview/requirements.txt
  - pip install coveralls

script:
  - coverage run --append -m unittest api_888_interview.api.test.test_event

after_success:
  - coveralls
