version: "2.0"

services:

  api:
    build:
      context: ./api_888_interview
      dockerfile: Dockerfile
    image: lfdivino/myapi
    container_name: api_888_interview
    restart: always
    expose:
      - 8080
    networks:
      - production-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    image: lfdivino/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - production-network
    depends_on:
      - api

networks:
  production-network:
    driver: bridge